name: yacrd_fpa

channels:
  - conda-forge
  - bioconda
  - pdrops

dependencies:
 - bwa=0.7.17
 - fpa=0.5
 - miniasm=0.3_r179
 - minimap2=2.17
 - mummer=3.23
 - python=3.6.7
 - quast=5.0.2
 - samtools=1.9
 - seqtk=1.3
 - wtdbg=2.3
 - yacrd=0.5.1     
